version: 2
updates: 
  - package-ecosystem: "nuget"
    directory: "/Backend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
      include: "scope"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/Backend/src/ShoeStore.Api"
    # Check for updates once a week
    schedule:
      interval: "daily"
