services:
  shoestore.api:
    image: hatranquang2006/shoestore-api:${TAG:-latest}
    container_name: ShoeStore_api
    build:
      context: .
      dockerfile: src/ShoeStore.Api/Dockerfile
    
    environment:
      - 
    
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
        

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

