services:
  shoestore.api:
    image: hatranquang2006/shoestore-api:${TAG:-latest}
    container_name: ShoeStore_api
    build:
      context: .
      dockerfile: src/ShoeStore.Api/Dockerfile
    
    environment:
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - GoogleAuthentication__ClientId=${GOOGLEAUTHENTICATION_CLIENTID}
      - FacebookAuthentication__Url=${FACEBOOKAUTHENTICATION_URL}
      - GoogleAuthentication__AppPassword=${GOOGLEAUTHENTICATION_APPPASSWORD}
      - Cloudinary__CloudName=${CLOUDINARY_CLOUDNAME}
      - Cloudinary__ApiKey=${CLOUDINARY_APIKEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_APISECRET}
      - Cloudinary__UploadPreset=${CLOUDINARY_UPLOADPRESET}
      - Sepay__ApiKey=${SEPAY_APIKEY}
      - ConnectionStrings__RedisConnection=${REDIS_CONNECTION}
      - Chatbot__ApiKey=${CHATBOT_APIKEY}
      - Chatbot__Url=${CHATBOT_URL}
      - Chatbot__Model=${CHATBOT_MODEL}
    
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    
    extra_hosts:
        - "host.docker.internal:host-gateway"
  
  cache:
    image: redis:8.6.1-alpine
    container_name: shoestore_cache
    ports:
      - "6379:6379"
    networks:
      - backend


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

