services:
  shoestore.api:
    image: hatranquang2006/shoestore-api:${TAG:-latest}
    container_name: ShoeStore_api
    build:
      context: .
      dockerfile: src/ShoeStore.Api/Dockerfile
    
    environment:
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
      - Jwt_Key=${JWT_KEY}
      - Jwt_Issuer=${JWT_ISSUER}
      - Jwt_Audience=${JWT_AUDIENCE}
      - GoogleAuthentication_ClientId=${GOOGLEAUTHENTICATION_CLIENTID}
    
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
        

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

