name: Backend SonarCloud Analysis

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  # --- JOB 1: TRINH SÁT ---
  detect-change:
    name: Scan File Changes
    runs-on: ubuntu-latest
    outputs:
      is_backend_changed: ${{ steps.filter.outputs.backend_code }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check path filters
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend_code:
              - 'Backend/**'

  # --- JOB 2: THỢ XÂY & MÁY QUÉT ---
  build-and-analyze:
    needs: detect-change # Lệnh chờ: Phải đợi thằng trinh sát làm xong
    if: needs.detect-change.outputs.is_backend_changed == 'true' # Lệnh chạy: Cờ true mới làm
    
    name: Backend Build and Analyze
    runs-on: ubuntu-latest
        
    defaults:
      run:
        working-directory: ./Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          sparse-checkout: |
            Backend
            
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          # Chìa khóa này chỉ thay đổi khi bạn thêm/bớt thư viện trong các file .csproj
          key: ${{ runner.os }}-nuget-${{ hashFiles('Backend/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' 

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          dotnet sonarscanner begin \
            /k:"tqha1011_ShoeStore" \
            /o:"tqha1011" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

      - name: Restore dependencies
        run: dotnet restore 

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: End SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
