name: Frontend SonarCloud Analysis

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  detect-change:
    name: Scan File Changes
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    outputs:
      is_frontend_changed: ${{ steps.filter.outputs.frontend_code }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check path filters
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend_code:
              - 'Frontend/**'

  build-and-analyze:
    needs: detect-change
    if: needs.detect-change.outputs.is_frontend_changed == 'true'
    name: Frontend Build and Analyze
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    defaults:
      run:
        working-directory: ./Frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Quan trọng để SonarCloud so sánh code
          sparse-checkout: |
            Frontend
            gradle
      - name: debug
        working-directory: .
        run: ls -la

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          # Chìa khóa này sẽ thay đổi nếu bất kỳ file build.gradle hoặc wrapper nào thay đổi
          key: ${{ runner.os }}-gradle-v2-${{ hashFiles('Frontend/**/*.gradle*', 'Frontend/gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21 # Gradle và SonarCloud cho Android chạy trên Java 17
          distribution: 'zulu' 

      # BƯỚC QUAN TRỌNG: Cấp quyền thực thi cho Gradle Wrapper
      - name: Make gradlew executable
        run: chmod +x gradlew

      # CHẠY QUÉT: Gradle sẽ tự động làm hết mọi việc trong 1 lệnh duy nhất
      - name: Build and Analyze with Gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          ./gradlew sonarqube -Dsonar.coverage.exclusions="**/*" \
            -Dsonar.projectKey=tqha1011_ShoeStore_Frontend \
            -Dsonar.organization=tqha1011 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN
            -Dsonar.c.file.suffixes=- \
            -Dsonar.cpp.file.suffixes=- \
            -Dsonar.objc.file.suffixes=-
