name: Frontend SonarCloud Analysis

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  detect-change:
    name: Scan File Changes
    runs-on: ubuntu-latest
    outputs:
      is_frontend_changed: ${{ steps.filter.outputs.frontend_code }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check path filters
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend_code:
              - 'Frontend/**'

  build-and-analyze:
    needs: detect-change
    if: needs.detect-change.outputs.is_frontend_changed == 'true'
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Frontend 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Quan trọng để SonarCloud so sánh code
          sparse-checkout: |
            /Frontend 

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17 # Gradle và SonarCloud cho Android chạy trên Java 17
          distribution: 'zulu' 

      # BƯỚC QUAN TRỌNG: Cấp quyền thực thi cho Gradle Wrapper
      - name: Make gradlew executable
        run: chmod +x gradlew

      # CHẠY QUÉT: Gradle sẽ tự động làm hết mọi việc trong 1 lệnh duy nhất
      - name: Build and Analyze with Gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=tqha1011_ShoeStore \
            -Dsonar.organization=tqha1011 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN
